### ISSUE TITLE
RecBigFile Demo is not working

### ISSUE THREAD

**Issue by cl3386** [quincyhuang/MCMCFrameworks_Public_Repo#7]
Hi, Author. First of all, I am very satisfied of your repo, and unity asset.

I am testing on upython2 pro and struggling from the RecBigFile Demo.

It seems that connection is not established because I am not seeing any console message from both Unity and CMD. CMD says "listening..." and that's all it says. SendBigFile Demo is working great, so I am asking what I am missing or potential issue on Receiving Big File task.

Best, and thanks in advance :)

**Comment by HaikunHuang** [comment]
Did you  run serverFTR.py before calling it? Also, make sure the python working directory is proper and the file path is correct.

**Comment by cl3386** [comment]
Thanks for quick response. I just add keyboard trigger in Update(), then it gets receiving file properly :)

**Comment by HaikunHuang** [comment]
Ah, I see. I think this issues caused by the script execution order. But if you use any trigger triggers the calls, that would not be a problem.  If you can make the UPython main script in a lower script execution order, then I think you can run any calls in Awake or Start functions with no problem.  👍

**Comment by HaikunHuang** [comment]
I will update the documentation.
